In [3]:
import numpy as np

In [5]:
print(np.__version__)

2.3.1


#asarray() with nditer()
#
#frombuffer()
#
#fromiter()

In [10]:
a=np.array(10)
print(a)

10


In [23]:

a=np.array([10,20,30], dtype=int, order="c")
print(a)
for i in np.nditer(a):
    print(i)

[10 20 30]
10
20
30


In [26]:
#Two dimension array
a=np.array([[10,20],[40,50]],order="f")  # Order " F " will give colounm wise order of an array 
for i in np.nditer(a):                           #" C " will give row wise order of an array
    print(i)
print(a)

10
40
20
50
[[10 20]
 [40 50]]


In [13]:
# 3D array
a=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [15]:
print(a[0][0][0])

10


In [36]:
x=b"python developer"
b=np.frombuffer(x,dtype="S2", count=5,offset=1)
print(b)

[b'yt' b'ho' b'n ' b'de' b've']


In [39]:
a=np.fromiter([1,2,3,4],dtype=int,count=3) # fromiter() is used to get the elements that we need using count
print(a)

[1 2 3]


#zeros()
#
full()
#
random.rand()
#
ones()
#
eye()


In [45]:
# inisializing
a=np.zeros([2,3,3],dtype=int)
print(a)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
