In [3]:
import numpy as np

In [5]:
print(np.__version__)

2.3.1


#asarray() with nditer()
#
#frombuffer()
#
#fromiter()

In [10]:
a=np.array(10)
print(a)

10


In [23]:

a=np.array([10,20,30], dtype=int, order="c")
print(a)
for i in np.nditer(a):
    print(i)

[10 20 30]
10
20
30


In [26]:
#Two dimension array
a=np.array([[10,20],[40,50]],order="f")  # Order " F " will give colounm wise order of an array 
for i in np.nditer(a):                           #" C " will give row wise order of an array
    print(i)
print(a)

10
40
20
50
[[10 20]
 [40 50]]


In [13]:
# 3D array
a=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [15]:
print(a[0][0][0])

10


In [36]:
x=b"python developer"
b=np.frombuffer(x,dtype="S2", count=5,offset=1)
print(b)

[b'yt' b'ho' b'n ' b'de' b've']


In [39]:
a=np.fromiter([1,2,3,4],dtype=int,count=3) # fromiter() is used to get the elements that we need using count
print(a)

[1 2 3]


#zeros()
#
full()
#
random.rand()
#
ones()
#
eye()


In [ ]:
# inisializing
a=np.zeros([2,3,3],dtype=int)
print(a)
print(a.ndim) #  gives which dimension of array it is
print(a[0,1,1]) # indexing

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
3
0


In [ ]:
# full
a=np.full([2,3,4],8)# it will take dimensions and value 
print(a)

[[[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]

 [[8 8 8 8]
  [8 8 8 8]
  [8 8 8 8]]]


In [ ]:
# Random.rand
print(np.random.rand(2,3)) # gives random values in 0 to 1 in given dimensions 

[[0.48050898 0.97843753 0.12650395]
 [0.10311115 0.40709635 0.98715081]]


In [111]:
print(np.ones([2,3]))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.eye(3)) # generate 1 for all diagnol elements 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [116]:
print(np.arange(1,9,2))

[1 3 5 7]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8]) # to reshape it into 2d array
print(a.reshape(4,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [128]:
print(a)
print(a.size)
print(a.shape)
print(a.dtype)

[1 2 3 4 5 6 7 8]
8
(8,)
int64


In [131]:
a=np.array([[1,2,3],[5,6,7]])
print(a.size)
print(a.shape)
print(a.dtype)

6
(2, 3)
int64
